on:
  push:
    branches:
    - master
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: cargo test
    - run: cargo run
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - name: Publish
      if: startsWith( github.ref, 'refs/tags/')
      run: npx vsce publish --pat ${{ secrets.VSCE_PAT }}
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: thrust-*.vsix